CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE note (
    note_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR (255),
    content VARCHAR (255),
    email VARCHAR(255)
);